### ISSUE TITLE
Create an example package that wraps the lahman dataset

### ISSUE THREAD

**Issue by machow** [dgrtwo/dbcooper#12]
Currently, there are two ways to use dbcooper:

* **from a script**: shown in readme, a quick way to get started.
* **wrapped by a package** shown in [stackbigquery](https://github.com/dgrtwo/stackbigquery) example, nice for sharing w/ analytics team.

Overall, it's very quick to start from a script, but a lot trickier to build a package. stackbigquery seems like a great comprehensive example, but takes a bit of time to figure out (e.g. requires some finagling to connect to bigquery; harder to run locally).

What if we made a trimmed down example package? Here's a rough pitch:

* Use the lahman dataset and sqlite
* Only have a `zzz.R` file, and one other file with a custom function (e.g. `summarize_xxx`)
* Add a "development" section to the readme (see [this comment](https://github.com/machow/dbpath/pull/5#issuecomment-1344384847) by @gadenbuie)

**Comment by chriscardillo** [comment]
Please see [lahmancooper](https://github.com/chriscardillo/lahmancooper)! 

Will close this issue. If you have any feedback about the package, let's address in the `lahmancooper` repo?
