### ISSUE TITLE
Support for database schemas

### ISSUE THREAD

**Issue by adam-gruer** [dgrtwo/dbcooper#6]
Lots of databases have schemas . At the moment the _tbl functions fail if the table is not part of the default schema for the database.  Would be great if you could add support for this.
For example if the lahman database had three schemas : the default,  dev, production
then there would be batting_tbl, dev_batting_tbl and production_batting_tbl functions and perhaps the lahman_tbl function could take an optional schema argument

**Comment by chriscardillo** [comment]
Hi, @adam-gruer!

The `dbc_init` allows you to pass in a list of table names, and each of those table names can include schemas.

So building on the above example, the process to create accessor functions which include schemas would be:

1. Establish a connection to your database. Let's call it `my_con`.
2. With `my_con`, obtain a list of all `schema.table` names (most likely by querying the information schema). Let's call it `my_table_list`.
3. Pass that list to `dbc_init`, like so: `dbc_init(my_con, my_table_list)`.

Hope this helps!

**Comment by chriscardillo** [comment]
@adam-gruer - going to close this issue, as Snowflake and Postgres schemas are directly supported, and the above can cover other databases. If there is a specific DB for which you require schemas, feel free to re-open this issue!
